name: absensi_tunas_jaya
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.3.2
  geolocator: ^13.0.1
  device_info_plus: ^10.1.0
  image_picker: ^1.1.2
  table_calendar: ^3.1.2
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  image: ^4.2.0
  file_picker: ^11.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/Star.png
    - assets/images/Light.png
    - assets/images/logo_tunas_jaya.png
    - assets/images/Ellipse_1.png
    - assets/images/Ellipse_2.png
    - assets/images/Picture.png
    - assets/images/message_fill.png
    - assets/images/lock.png
    - assets/images/Bubbles.png
    - assets/images/Verified.png
    - assets/images/handclick.png
    - assets/images/masuk.png
    - assets/images/keluar.png
    - assets/images/totaljam.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700

    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300